# -*- coding: utf-8 -*-
"""
Generate npc_abilities_custom.txt from 技能表.xlsx
Based on the Row 2 mapping (English keys) and the data structure.
"""
import openpyxl

wb = openpyxl.load_workbook('技能表.xlsx')
ws = wb.active

# Row 2 contains the English KV key names
# Read the mapping
headers_cn = []
headers_en = []
for col in range(1, ws.max_column + 1):
    headers_cn.append(ws.cell(1, col).value or '')
    headers_en.append(ws.cell(2, col).value or '')

output_lines = [
    '',
    '// this file is auto-generated by Xavier\'s sheet_to_kv from',
    '// 技能表.xlsx npc_abilities_custom',
    '// SourceCode: https://github.com/XavierCHN/gulp-dotax/blob/master/src/sheetToKV.ts',
    '// Template: https://github.com/XavierCHN/x-template',
    '"XLSXContent" {',
]

for row in range(3, ws.max_row + 1):
    name = ws.cell(row, 1).value
    if not name:
        continue

    output_lines.append(f'\t"{name}" {{')

    # Simple key-value fields (cols 2-17)
    simple_fields = {
        2: 'BaseClass',
        3: 'ScriptFile',
        4: 'AbilityTextureName',
        5: 'AbilityBehavior',
        6: 'MaxLevel',
        7: 'AbilityCooldown',
        8: 'AbilityManaCost',
        9: 'AbilityType',
        10: 'AbilityUnitDamageType',
        11: 'AbilityCastRange',
        12: 'AbilityCastPoint',
        13: 'AbilityUnitTargetTeam',
        14: 'AbilityUnitTargetType',
        15: 'AbilityCategory',
        16: 'AbilityStar',
        17: 'AbilityElement',
    }

    for col, kv_key in simple_fields.items():
        val = ws.cell(row, col).value
        if val is not None:
            output_lines.append(f'\t\t"{kv_key}" "{val}"')

    # AbilityValues block (cols 19-28, each is "key value" format)
    has_values = False
    value_lines = []
    for col in range(19, 29):
        val = ws.cell(row, col).value
        if val is not None:
            parts = str(val).split(' ', 1)
            if len(parts) == 2:
                value_lines.append(f'\t\t\t"{parts[0]}" "{parts[1]}"')
            else:
                value_lines.append(f'\t\t\t"{parts[0]}" ""')
            has_values = True

    if has_values:
        output_lines.append('\t\t"AbilityValues" {')
        output_lines.extend(value_lines)
        output_lines.append('\t\t}')

    # Precache block (cols 31-32)
    particle = ws.cell(row, 31).value
    sound = ws.cell(row, 32).value
    if particle or sound:
        output_lines.append('\t\t"Precache" {')
        if particle:
            output_lines.append(f'\t\t\t"particle" "{particle}"')
        if sound:
            output_lines.append(f'\t\t\t"soundfile" "{sound}"')
        output_lines.append('\t\t}')

    output_lines.append('\t}')

output_lines.append('}')
output_lines.append('')

# Write to npc_abilities_custom.txt
output_path = '../game/scripts/npc/npc_abilities_custom.txt'
with open(output_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(output_lines))

print(f'Generated {output_path} with {ws.max_row - 2} abilities')
